name: diagram generator

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/generator.yaml'
      - '**/*.drawio'

concurrency:
  group: diagrams-export-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generator:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout diagrams
        uses: actions/checkout@v2

      - name: get author and committer info from HEAD commit
        if: github.ref == 'refs/heads/master'
        uses: rlespinasse/git-commit-data-action@v1.x

      - name: flatten
        run: |
          mkdir artifacts
          mkdir flatten
          find . -name \*.drawio -not -path "./flatten/*" -exec sh -c 'echo {}; new=$(echo "{}" | cut -c 3- | tr " " "-" | tr "/" " "); cp "{}" "flatten/$new"' \;
      
      - name: build drawio files as svg
        uses: rlespinasse/drawio-export-action@v2
        with:
          path: flatten
          format: svg
          transparent: false
          remove-page-suffix: true
          output: ${{ github.workspace }}/artifacts
          action-mode: all

      - name: build drawio files as png
        uses: rlespinasse/drawio-export-action@v2
        with:
          path: flatten
          format: png
          transparent: false
          remove-page-suffix: true
          output: ${{ github.workspace }}/artifacts
          action-mode: all

      - name: unflatten
        run: |
          find artifacts -type f -exec sh -c 'echo {}; new=$(echo "{}" | tr " " "/"); folder=$(dirname "$new"); sudo mkdir -p "$folder" && mv "{}" "$new" || echo "same"' \;
          ls artifacts

      - name: README.md
        run: |
          echo "# Diagrams" > README.md

          for f in artifacts/*.svg; do
            echo "## ${f##*/}" >> README.md
            echo "![$f](https://github.com/AciesDK/core-diagrams/blob/$f?raw=true \"$f\")" >> README.md
          done

      - name: commit changed README.md
        id: commit-readme
        if: github.ref == 'refs/heads/master'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: 'README.md'
          commit_message: 'docs: sync draw.io exported files'
          branch: master

      - name: changes have been detected
        if: steps.commit-readme.outputs.changes_detected == 'true'
        run: echo 'Changes!'

      - name: no changes have been detected
        if: steps.commit-readme.outputs.changes_detected == 'false'
        run: echo 'No changes!'

      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: diagrams
          path: artifacts

      - name: clean up
        run: sudo rm -fr artifacts

      - name: checkout artifacts
        uses: actions/checkout@v2
        with:
          ref: artifacts

      - name: clear artifacts
        run: |
          git rm -r . || echo "no files"

      - name: download artifacts
        uses: actions/download-artifact@v2
        with:
          name: diagrams
          path: .

      - name: commit changed artifacts
        id: commit-artifacts
        if: github.ref == 'refs/heads/master'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'docs: sync draw.io exported files'
          branch: artifacts

      - name: changes have been detected
        if: steps.commit-artifacts.outputs.changes_detected == 'true'
        run: echo 'Changes!'

      - name: no changes have been detected
        if: steps.commit-artifacts.outputs.changes_detected == 'false'
        run: echo 'No changes!'
